spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: postgres
    initialization-mode: never
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
  main:
    allow-circular-references: true
    #allow-bean-definition-overriding: true

  batch:
    job:
      enabled: false
    shell:
      interactive:
        enabled: true
    initialize-schema: always

  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb
      username: userAdmin
      password: password


  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    show-sql: true


logging:
 level:
   ROOT: INFO