ALTER TABLE book_comments
DROP CONSTRAINT IF EXISTS fk_book_comment;

ALTER TABLE books
DROP CONSTRAINT IF EXISTS fk_book_author;

ALTER TABLE books
DROP CONSTRAINT IF EXISTS fk_book_genre;

drop table if exists authors cascade

drop table if exists book_comments cascade

drop table if exists books cascade

drop table if exists genres cascade

create table authors (
                         id int8 generated by default as identity,
                         name varchar(255) not null,
                         primary key (id)
)

create table book_comments (
                               id int8 generated by default as identity,
                               book_id int8  references books(id) on delete cascade,
                               text varchar(255) not null,
                               primary key (id)
)

create table books (
                       id int8 generated by default as identity,
                       title varchar(255),
                       author_id int8,
                       genre_id int8,
                       primary key (id)
)

create table genres (
                        id int8 generated by default as identity,
                        title varchar(255) not null,
                        primary key (id)
)

ALTER TABLE books
    ADD CONSTRAINT fk_book_author
        foreign key (author_id)
            REFERENCES authors (id);

ALTER TABLE books
    ADD CONSTRAINT fk_book_genre
        foreign key (genre_id)
            REFERENCES genres (id);

/*ALTER TABLE book_comments
    ADD CONSTRAINT fk_book_comment
        foreign key (book_id)
            REFERENCES books (id);*/
