spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: postgres
    #initialization-mode: always
    #schema: schema.sql
    #data: data.sql
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
  main:
    allow-circular-references: true