alter table if exists book_comments
drop constraint if exists FK6xpmpddanwk8vq96sax69c4hu;


alter table if exists books
drop constraint if exists FKfjixh2vym2cvfj3ufxj91jem7;


alter table if exists books
drop constraint if exists FK9hsvoalyniowgt8fbufidqj3x;


drop table if exists authors cascade;


drop table if exists book_comments cascade;


drop table if exists books cascade;


drop table if exists genres cascade;


create table authors (
                         id int8 generated by default as identity,
                         name varchar(255) not null,
                         primary key (id)
);


create table book_comments (
                               id int8 generated by default as identity,
                               text varchar(255) not null,
                               book_id int8,
                               primary key (id)
);


create table books (
                       id int8 generated by default as identity,
                       title varchar(255),
                       author_id int8,
                       genre_id int8,
                       primary key (id)
);


create table genres (
                        id int8 generated by default as identity,
                        title varchar(255) not null,
                        primary key (id)
);


alter table if exists authors
    add constraint UK_9mhkwvnfaarcalo4noabrin5j unique (name);


alter table if exists genres
    add constraint UK_bjvsqv7pyof67ud2ys7vff2y4 unique (title);


alter table if exists book_comments
    add constraint FK6xpmpddanwk8vq96sax69c4hu
    foreign key (book_id)
    references books;


alter table if exists books
    add constraint FKfjixh2vym2cvfj3ufxj91jem7
    foreign key (author_id)
    references authors;


alter table if exists books
    add constraint FK9hsvoalyniowgt8fbufidqj3x
    foreign key (genre_id)
    references genres;
