spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb
      username: userAdmin
      password: password
  main:
    allow-circular-references: true


mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.book.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local


logging:
  level:
    ROOT: ERROR